# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganbatte < Formula
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.3.0/ganbatte_darwin_amd64.tar.gz"
      sha256 "b690f2cebb971290f6eef314503db8f0ea449271c567e8d6eceec514ccd719b1"

      define_method(:install) do
        bin.install "gnb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.3.0/ganbatte_darwin_arm64.tar.gz"
      sha256 "c3f9a026b779e23cdb4dca3fd4f535967e4f7710cb87ca3230d46d962eb91e3e"

      define_method(:install) do
        bin.install "gnb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.3.0/ganbatte_linux_amd64.tar.gz"
      sha256 "555c6c97ebb61a00603bceefee854c23f44812e3ad0c14eaf462fda8ecea3ff2"
      define_method(:install) do
        bin.install "gnb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.3.0/ganbatte_linux_arm64.tar.gz"
      sha256 "b0fe55e8757a2910368f90900212fb5e3f415a3e44079924dd3ae04599e702af"
      define_method(:install) do
        bin.install "gnb"
      end
    end
  end

  test do
    system "#{bin}/gnb", "--help"
  end
end
