# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ganbatte < Formula
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"
  version "1.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.5.7/ganbatte_darwin_amd64.tar.gz"
      sha256 "8b078f575a423f769c7a7b8d04d97d2ea5f2942ae475ef011cb1435ec7b63f6c"

      define_method(:install) do
        bin.install "gnb"
        generate_completions_from_executable(bin/"gnb", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.5.7/ganbatte_darwin_arm64.tar.gz"
      sha256 "74d60f53cc7ddbeac7e63b0fad995e4c520e3781f505c359847fe8fc1bd8e0f5"

      define_method(:install) do
        bin.install "gnb"
        generate_completions_from_executable(bin/"gnb", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.5.7/ganbatte_linux_amd64.tar.gz"
      sha256 "d6782e064a07c0a4f2fe51d773f7fe7f5e3391ec7ced8387d289690f0cfa7475"
      define_method(:install) do
        bin.install "gnb"
        generate_completions_from_executable(bin/"gnb", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bssm-oss/ganbatte/releases/download/v1.5.7/ganbatte_linux_arm64.tar.gz"
      sha256 "67a8c90b6c8411acf0c2d96a432a49a5a11a3437e901c2be0284864c0cda8a32"
      define_method(:install) do
        bin.install "gnb"
        generate_completions_from_executable(bin/"gnb", "completion")
      end
    end
  end

  test do
    system "#{bin}/gnb", "--help"
  end
end
