# This file was generated by GoReleaser. DO NOT EDIT.
cask "ganbatte" do
  version "1.5.4"

  on_macos do
    on_intel do
      sha256 "c1232f678a2ddf54bba94a29822933f99c869fefb07f2c117754e18d66d4d393"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18ce8591bc118a16805f818ea0c50199ca878ed656e20b2b901891969efe4479"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "507ea30ceb396ecd615bb421ae3dbbca8d5ab1fb70f7736cde66ee01f25236d9"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05bd8b61451eaec443638e669433dee7041cae678bf1023271d608869454aa7f"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_arm64.tar.gz"
    end
  end

  name "ganbatte"
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gnb"
  generate_completions_from_executable "bin/gnb", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
