# This file was generated by GoReleaser. DO NOT EDIT.
cask "ganbatte" do
  version "1.5.5"

  on_macos do
    on_intel do
      sha256 "ab3419947de9f00ef7eb94edc68610f8abf7eacbd6f5c683fdeb7005d7ebe4ef"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4586f6bd314ada894b7b345283e7c1f707b806b738bc4f6ccdca4758c868444"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b33eaf86b28ae079fceafa1924d7117dd54ad0670ebc830940ee7be882d25ced"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e02e880c3365fef06c83877f552bcca58643bf964cde4a8a27cbbf5178d4e570"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_arm64.tar.gz"
    end
  end

  name "ganbatte"
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gnb"
  generate_completions_from_executable "bin/gnb",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
