# This file was generated by GoReleaser. DO NOT EDIT.
cask "ganbatte" do
  version "1.5.6"

  on_macos do
    on_intel do
      sha256 "d500b211a7a22fcbe888fb08e8711eef8015b80a3bf26508921a120a82cca2b9"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d3250b4f02a9aadde38e2343a837f97a2ecf9253e574ba198fb29a1bcad12a1"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f66f283599ae3d7925731333b0ab3471537eb7ec000407e31e66681eff7b159"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9568a1357f43b67b869287020f84118c95b5b7be09fb58f2daa949a0f460b468"
      url "https://github.com/bssm-oss/ganbatte/releases/download/v#{version}/ganbatte_linux_arm64.tar.gz"
    end
  end

  name "ganbatte"
  desc "Workflow/shortcut management CLI for lazy developers"
  homepage "https://github.com/bssm-oss/ganbatte"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gnb"
  generate_completions_from_executable "gnb",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
